version: "3"

services:
  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes:
      - ./db/me/reactive/conf.d:/etc/mysql/conf.d
      - ./db/me/reactive/data:/var/lib/mysql
    env_file: .env
    platform: linux/x86_64
    networks:
      - backend
    restart: always

networks:
  backend:
